# Configuração básica
title: João Nunes - Software Developer
description: Portfólio profissional de João Nunes
theme: minimal

# URL base (use apenas se o site estiver em um subdiretório)
baseurl: "/portfolio" # Altere conforme o nome do repositório

# Idioma do site
lang: en

# Links de navegação
navigation:
  - name: "Sobre"
    url: "/#about"
  - name: "Projetos"
    url: "/#projects"
  - name: "Contactos"
    url: "/#contact"

# Redes sociais
social_links:
  github: "https://github.com/joaonunesss"
  linkedin: "https://linkedin.com/in/jpmnunes"

# Plugins (se necessários)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
